name: pekan_innovasi
description: "Aplikasi Pekan Inovasi"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '^3.6.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Firebase Core & Services
  firebase_core: ^3.4.0
  firebase_auth: ^5.3.0
  firebase_messaging: ^15.1.0
  cloud_firestore: ^5.4.3
  firebase_storage: ^12.4.5  # atau versi terbaru

  # Auth & Sosial Login
  google_sign_in: ^6.2.1

  # UI & Utilitas
  fluttertoast: ^8.2.8
  flutter_spinkit: ^5.2.1
  font_awesome_flutter: ^10.7.0
  flutter_gif: ^0.0.4
  cached_network_image: ^3.4.0
  fl_chart: ^0.71.0
  particles_flutter: ^1.0.1
  url_launcher: ^6.3.0

  # background service
  flutter_background_service: ^5.0.1
  location: ^5.0.0
  flutter_background_service_android: ^6.3.0



  # Geolocation & Maps
  geolocator: ^12.0.0 
  google_maps_flutter: ^2.9.0
  flutter_map: ^8.1.1

  # Kamera & File
  image_picker: ^1.1.2

  # Data & State Management
  http: ^1.2.2
  shared_preferences: ^2.3.0
  provider: ^6.1.5
  json_annotation: ^4.9.0
  intl: ^0.20.2

  # Komunikasi & Suara
  web_socket_channel: ^3.0.1
  speech_to_text: ^7.0.0
  flutter_tts: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.12
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - images/logo.png
    - images/Logo_BNPB.png
    - images/Logo_BMKG.png
    - images/BOT.png
    - images/Connecting teams-bro.png